---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app-k
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=888332437124.dkr.ecr.us-east-1.amazonaws.com/interview/nodejs-simple-app
    argocd-image-updater.argoproj.io/app.update-strategy: latest
    argocd-image-updater.argoproj.io/app.kustomize.image-name: 888332437124.dkr.ecr.us-east-1.amazonaws.com/interview/nodejs-simple-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/OmriUniversity/nodejs-app-deployment.git
    targetRevision: main
    path: environment/staging/nodejs-app-k
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true