---
namespace: staging
replicas:
  - name: nodej-deployment
    count: 2
images:
  - name: 888332437124.dkr.ecr.us-east-1.amazonaws.com/interview/nodejs-simple-app
    newTag: latest
resources:
  - ../../../nodejs-app-base

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: dockerconfigjson }]