---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-foo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/OmriUniversity/nodejs-app-deployment.git
    targetRevision: HEAD
    path: environments/staging/nodejs-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    preserveResourcesOnDeletion: false
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true